### ISSUE TITLE
突然不能用了

### ISSUE THREAD

**Issue by iErics** [HouCoder/tele-aria2#17]
报错信息如下：
`internal/fs/utils.js:230
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tele-aria2/dist/run.js:44:46)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
`

**Comment by Acheng-dot** [comment]
我也出现了这种而错误，你是否已经解决

**Comment by iErics** [comment]
> 我也出现了这种而错误，你是否已经解决

没有解决，可能是docker镜像出问题了，在等作者

**Comment by HouCoder** [comment]
最近有点忙，打算明年再做一个 major release，到时候来看下这个问题。

**Comment by lloyd18** [comment]
@HouCoder 大佬，你开始新建文件夹了吗

**Comment by HouCoder** [comment]
尴尬，平时不怎么用这个工具了，我买了一个白群晖，平时都是用群晖的 Download Station 了 😅
