### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by ferbulous** [HouCoder/tele-aria2#18]
Hi, I'm trying to run the docker on my raspbian but I'm getting this error instead

```
     
internal/fs/utils.js:230

    throw err;

    ^



Error: EISDIR: illegal operation on a directory, read

    at Object.readSync (fs.js:564:3)

    at tryReadSync (fs.js:349:20)

    at Object.readFileSync (fs.js:386:19)

    at Object.<anonymous> (/usr/local/lib/node_modules/tele-aria2/dist/run.js:44:46)

    at Module._compile (internal/modules/cjs/loader.js:1138:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

    at Module.load (internal/modules/cjs/loader.js:986:32)

    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

    at internal/main/run_main_module.js:17:47 {

  errno: -21,

  syscall: 'read',

  code: 'EISDIR'

}

```

What could be the issue here?

**Comment by HouCoder** [comment]
`illegal operation on a directory`

Seems you made some mistake in the folder or file path.
