### ISSUE TITLE
tele-aria2 --bot-key not working for me :(

### ISSUE THREAD

**Issue by billouetaudrey** [HouCoder/tele-aria2#37]
Hi,

anyone can help me or abandoned ?

```
billou@billou-serveur:~$ tele-aria2 --bot-key ***
/usr/lib/node_modules/tele-aria2/dist/run.js:58
var userId = options.userId.split(',').map(Number);
                            ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/tele-aria2/dist/run.js:58:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

Thanks

**Comment by billouetaudrey** [comment]
Fixed
tele-aria2 --aria2-server=*** --aria2-key=*** --bot-key=*** --user-id=*** :)
